name: Multi

on:
  push:
    branches:
      - main

jobs:

   run-on-ubuntu1:
    runs-on: ubuntu-latest
    if: always()  # This ensures the job runs even if previous jobs fail
    

    steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
        php-version: 8
     - name: Run Php Program
     
       run :
          php a.php
          
          

